environment:
  matrix:
  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 37
  - TOXENV: py37
    PYTHON_PATH: C:\Python37
    JEDI_TEST_ENVIRONMENT: 36

  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 37
  - TOXENV: py36
    PYTHON_PATH: C:\Python36
    JEDI_TEST_ENVIRONMENT: 36
install:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install tox
build_script:
  - tox
